### ISSUE TITLE
tcc package not available on conan

### ISSUE THREAD

**Issue by quic-egmc** [Minres/TGC-ISS#2]
https://github.com/Minres/TGC-ISS/blob/033fa1eede7b5e180dc4435783cbe31154003d71/CMakeLists.txt#L75

the tcc package is not available on conan from what I can see

**Comment by eyck** [comment]
tcc can be pulled from https://git.minres.com/api/packages/Tooling/conan by calling
```
conan remote add gitea https://git.minres.com/api/packages/Tooling/conan
```

**Comment by quic-egmc** [comment]
thanks @eyck !

**Comment by eyck** [comment]
If you need any further help, you can email me directly.
